spring:
  cloud:
    stream:
      bindings:
        output:
          destination: tweets/stream
          binder: local_solace
      binders:
        local_solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: default
                clientPassword: default
                connectRetries: 3
                connectRetriesPerHost: 0                
                reconnectRetries: 3
logging:
  level:
    root: INFO
    com.solacesystems.jcsmp: INFO
    org.springframework: INFO

server:
  port: 8095
